# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AgoraWithFaceunity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Nama', '~> 6.2.0'
  # Pods for AgoraWithFaceunity

end
